"""add_user_record_10

Revision ID: 005acb9e7f65
Revises: aa04791c8b79
Create Date: 2026-03-01 20:47:55.797433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005acb9e7f65'
down_revision: Union[str, Sequence[str], None] = 'aa04791c8b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_song_artist_trgm'), table_name='song', postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_song_name_trgm'), table_name='song', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_song_search_vector'), table_name='song', postgresql_using='gin')
    op.drop_column('song', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('(setweight(to_tsvector(\'simple\'::regconfig, (COALESCE(name, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'simple\'::regconfig, (COALESCE(artist, \'\'::character varying))::text), \'B\'::"char"))', persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_song_search_vector'), 'song', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_song_name_trgm'), 'song', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_song_artist_trgm'), 'song', ['artist'], unique=False, postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
