"""song_level_cascaed

Revision ID: 112e5489e801
Revises: 44ecbf213e46
Create Date: 2026-03-11 19:53:07.053945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112e5489e801'
down_revision: Union[str, Sequence[str], None] = '44ecbf213e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('song_level_id_fkey'), 'song', type_='foreignkey')
    op.create_foreign_key(None, 'song', 'level', ['level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.create_foreign_key(op.f('song_level_id_fkey'), 'song', 'level', ['level_id'], ['id'])
    op.alter_column('song', 'level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
