"""modal_add

Revision ID: 197e0c589f6c
Revises: 8db3cd04cea2
Create Date: 2026-02-15 13:15:28.924747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197e0c589f6c'
down_revision: Union[str, Sequence[str], None] = '8db3cd04cea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gstring',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('normal', 'coting', name='gstringenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('string_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_string_id'), 'user', ['string_id'], unique=False)
    op.create_foreign_key(None, 'user', 'gstring', ['string_id'], ['id'])
    op.drop_column('user', 'string')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_string_id'), table_name='user')
    op.drop_column('user', 'string_id')
    op.drop_table('gstring')
    # ### end Alembic commands ###
