"""add_category_6

Revision ID: 34035047d507
Revises: 15d1b17f447d
Create Date: 2026-02-26 23:54:36.620227

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34035047d507'
down_revision: Union[str, Sequence[str], None] = '15d1b17f447d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('song', sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('song', sa.Column('style', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('song', sa.Column('speed', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('song', sa.Column('level_id', sa.Integer(), nullable=True))
    op.add_column('song', sa.Column('chord', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('song', sa.Column('tube_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('song', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_song_level_id'), 'song', ['level_id'], unique=False)
    op.create_foreign_key(None, 'song', 'level', ['level_id'], ['id'])
    op.add_column('user', sa.Column('device', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'modal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_user_device'), 'user', ['device'], unique=True)
    op.create_unique_constraint(None, 'user', ['device_id'])
    op.drop_column('user', 'machinery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('machinery', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_device'), table_name='user')
    op.alter_column('user', 'modal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('user', 'device_id')
    op.drop_column('user', 'device')
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_index(op.f('ix_song_level_id'), table_name='song')
    op.drop_column('song', 'file_url')
    op.drop_column('song', 'tube_url')
    op.drop_column('song', 'chord')
    op.drop_column('song', 'level_id')
    op.drop_column('song', 'speed')
    op.drop_column('song', 'style')
    op.drop_column('song', 'artist')
    op.drop_column('song', 'name')
    # ### end Alembic commands ###
