"""n:n_8

Revision ID: 3c0385963d53
Revises: 34035047d507
Create Date: 2026-02-28 22:08:46.562579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0385963d53'
down_revision: Union[str, Sequence[str], None] = '34035047d507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songcategorylink',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'category_id')
    )
    op.add_column('user', sa.Column('is_device', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_user_device'), table_name='user')
    op.drop_constraint(op.f('user_device_id_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_device_id'), 'user', ['device_id'], unique=True)
    op.drop_column('user', 'device')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('device', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_device_id'), table_name='user')
    op.create_unique_constraint(op.f('user_device_id_key'), 'user', ['device_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_device'), 'user', ['device'], unique=True)
    op.drop_column('user', 'is_device')
    op.drop_table('songcategorylink')
    # ### end Alembic commands ###
