"""add user_song_click

Revision ID: 44ecbf213e46
Revises: 133af9dd9a29
Create Date: 2026-03-11 19:05:50.256307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44ecbf213e46'
down_revision: Union[str, Sequence[str], None] = '133af9dd9a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songuserclickedlink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'song_id')
    )
    op.drop_index(op.f('idx_song_artist_trgm'), table_name='song', postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_song_name_trgm'), table_name='song', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_song_search_vector'), table_name='song', postgresql_using='gin')
    op.drop_column('song', 'search_vector')
    op.drop_index(op.f('idx_userrecord_name_trgm'), table_name='userrecord', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_userrecord_search_vector'), table_name='userrecord', postgresql_using='gin')
    op.drop_column('userrecord', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userrecord', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, (COALESCE(name, ''::character varying))::text)", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_userrecord_search_vector'), 'userrecord', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_userrecord_name_trgm'), 'userrecord', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('song', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('(setweight(to_tsvector(\'simple\'::regconfig, (COALESCE(name, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'simple\'::regconfig, (COALESCE(artist, \'\'::character varying))::text), \'B\'::"char"))', persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_song_search_vector'), 'song', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_song_name_trgm'), 'song', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_song_artist_trgm'), 'song', ['artist'], unique=False, postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table('songuserclickedlink')
    # ### end Alembic commands ###
