"""add_modal_in_usertable

Revision ID: 8db3cd04cea2
Revises: a9e025538e43
Create Date: 2026-02-14 13:45:43.193828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db3cd04cea2'
down_revision: Union[str, Sequence[str], None] = 'a9e025538e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modal', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modal')
    # ### end Alembic commands ###
