"""modal_add_col

Revision ID: a810adfd8d9f
Revises: bb4c2075d9a6
Create Date: 2026-02-15 18:34:32.627526

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a810adfd8d9f'
down_revision: Union[str, Sequence[str], None] = 'bb4c2075d9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gstring', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('guitar', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('level', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level', 'name')
    op.drop_column('guitar', 'name')
    op.drop_column('gstring', 'name')
    # ### end Alembic commands ###
