"""create_table

Revision ID: a9e025538e43
Revises: 
Create Date: 2026-02-11 19:03:15.738851

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e025538e43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guitar',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('g1', 'g2', 'g3', 'g4', name='guitarval'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('L1', 'L2', 'L3', 'L4', 'L5', name='levelstep'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('string', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machinery', sa.Boolean(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('guitar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guitar_id'], ['guitar.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_guitar_id'), 'user', ['guitar_id'], unique=False)
    op.create_index(op.f('ix_user_level_id'), 'user', ['level_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_level_id'), table_name='user')
    op.drop_index(op.f('ix_user_guitar_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('level')
    op.drop_table('guitar')
    # ### end Alembic commands ###
