"""modal_modification

Revision ID: bb4c2075d9a6
Revises: 197e0c589f6c
Create Date: 2026-02-15 15:24:27.316341

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb4c2075d9a6'
down_revision: Union[str, Sequence[str], None] = '197e0c589f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gstring', 'step',
               existing_type=postgresql.ENUM('normal', 'coting', name='gstringenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('guitar', 'step',
               existing_type=postgresql.ENUM('g1', 'g2', 'g3', 'g4', name='guitarval'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('level', 'step',
               existing_type=postgresql.ENUM('L1', 'L2', 'L3', 'L4', 'L5', name='levelstep'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('level', 'step',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('L1', 'L2', 'L3', 'L4', 'L5', name='levelstep'),
               existing_nullable=True)
    op.alter_column('guitar', 'step',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('g1', 'g2', 'g3', 'g4', name='guitarval'),
               existing_nullable=True)
    op.alter_column('gstring', 'step',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('normal', 'coting', name='gstringenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
