"""remove_guitar

Revision ID: fbf657384593
Revises: a6a22941b2a9
Create Date: 2026-03-17 17:17:18.543942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbf657384593'
down_revision: Union[str, Sequence[str], None] = 'a6a22941b2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('idx_song_artist_trgm'), table_name='song', postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_song_name_trgm'), table_name='song', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_song_search_vector'), table_name='song', postgresql_using='gin')
    op.drop_index(op.f('ix_user_guitar_id'), table_name='user')
    op.drop_constraint(op.f('user_guitar_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'guitar_id')
    op.drop_index(op.f('idx_userrecord_name_trgm'), table_name='userrecord', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_userrecord_search_vector'), table_name='userrecord', postgresql_using='gin')
    op.drop_table('guitar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_userrecord_search_vector'), 'userrecord', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_userrecord_name_trgm'), 'userrecord', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('user', sa.Column('guitar_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_guitar_id_fkey'), 'user', 'guitar', ['guitar_id'], ['id'])
    op.create_index(op.f('ix_user_guitar_id'), 'user', ['guitar_id'], unique=False)
    op.create_index(op.f('idx_song_search_vector'), 'song', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_song_name_trgm'), 'song', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_song_artist_trgm'), 'song', ['artist'], unique=False, postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_table('guitar',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('step', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guitar_pkey'))
    )
    # ### end Alembic commands ###
